# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '~>3.3.12'
gem 'middleman-livereload', '~>3.1.0'
gem 'middleman-cli'
gem 'middleman-blog'
